name: auth-naflows.com

services:

  mongo-nass:
    image: mongo:latest
    restart: always
    profiles: ["mongo-nass"]
    container_name: mongo-nass
    hostname: mongo-nass
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - auth-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: NASS
    logging:
      driver: none
    
    # DEVELOPMENT ONLY
    # REMOVE IN PRODUCTION
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M

  auth-api:
    build: ./
    restart: always
    profiles: ["auth-api"]
    container_name: auth-api-1
    environment:
      - AUTH_API_PORT=3000
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_URL=${MONGO_URL}
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - mongo-nass
    volumes:
      - ./:/app
    
    # DEVELOPMENT ONLY
    # REMOVE IN PRODUCTION
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 512M

        
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    profiles: ["mongo-express"]
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-nass
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo-nass:27017/
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      #Set password for admin user
      ME_CONFIG_SITE_ADMIN_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_SITE_ADMIN_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - mongo-nass

    logging:
      driver: none


  global-tests:
    build: ./
    profiles: ["test-global"]
    command: npm run test-global
    depends_on:
      - auth-api
      - mongo-nass
      - mongo-express
    volumes:
      - ./:/app
      - auth-data:/app/data
    environment:
      - NODE_ENV=test
      - AUTH_API_URL= ${AUTH_API_URL}
      

volumes:
  auth-data:
    driver: local
  mongo-data:
    driver: local
  mongo-express-data:
    driver: local
