name: auth-naflows.com
services:
  mongo-nass:
    image: mongo:latest
    restart: always
    profiles: ["mongo-nass"]
    container_name: mongo-nass
    hostname: mongo-nass
    networks:
      - nass-network
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: NASS
    

  auth-api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    profiles: ["auth-api","mongo-nass"]
    container_name: auth-api-1
    networks:
      - nass-network
    environment:
      - AUTH_API_PORT=3000
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_URL=${MONGO_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_SECURE=${SMTP_SECURE}
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - mongo-nass


  mongo-express:
    image: mongo-express
    container_name: mongo-express
    profiles: ["mongo-express"]
    networks:
      - nass-network
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-nass
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo-nass:27017/
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      #Set password for admin user
      ME_CONFIG_SITE_ADMIN_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_SITE_ADMIN_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - mongo-nass

    logging:
      driver: none

  dummy-api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    restart: always
    profiles: ["dummy-api"]
    container_name: dummy-api
    networks:
      nass-network:
        ipv4_address: 172.28.0.10
    ports:
      - "3005:3005"
    expose:
      - "3005"
  
     

        
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        DUMMY_API_URL: http://localhost/api/dummy
        AUTH_API_URL: http://localhost/api/auth
    restart: always
    profiles: ["frontend"]
    container_name: nass-frontend
    networks:
      - nass-network
    ports:
      - "8080:3000"

  methods-tests:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    profiles: ["methods-tests"]
    command: npm run methods-test
    depends_on:
      - mongo-nass
      - auth-api
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=test
      - AUTH_API_URL=${AUTH_API_URL}



volumes:
  auth-data:
    driver: local
  mongo-data:
    driver: local
  mongo-express-data:
    driver: local
  captcha-data:
    driver: local
networks:
  nass-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
